import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Code2, Edit3, Mail, ShieldCheck, Users } from 'lucide-react';
import { useAuth } from '../hooks/useAuth.jsx';
import { roomService } from '../services/room.js';
import { ProfileEditModal } from '../components/ProfileEditModal.jsx';

export const ProfilePage = () => {
  const { user, updateProfile } = useAuth();
  const [rooms, setRooms] = useState([]);
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState(false);
  const [bio, setBio] = useState(() => localStorage.getItem(`codesync-bio-${user?.id}`) || 'Developer focused on building software together.');
  useEffect(() => { let active = true; roomService.getMyRooms().then((data) => active && setRooms(Array.isArray(data) ? data : [])).catch(() => active && setRooms([])).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);
  const memberCount = useMemo(() => rooms.reduce((total, room) => total + (room.members?.length || 1), 0), [rooms]);
  const save = async (data) => { await updateProfile(data); setBio(localStorage.getItem(`codesync-bio-${user?.id}`) || bio); };
  return <main className="min-h-[calc(100dvh-4rem)] bg-[#020d13] px-4 py-8 text-slate-200 sm:px-6 sm:py-12"><div className="mx-auto max-w-5xl"><p className="font-mono text-[11px] uppercase tracking-[.2em] text-[#84dfff]">Account</p><div className="mt-3 flex flex-col justify-between gap-4 border-b border-cyan-100/10 pb-7 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-semibold tracking-[-.04em] text-white">Developer profile</h1><p className="mt-2 text-sm text-slate-400">Your CodeSync identity and workspace activity.</p></div><button onClick={() => setEditing(true)} className="inline-flex items-center justify-center gap-2 rounded-md border border-cyan-100/20 bg-[#071e2a] px-4 py-2.5 text-sm font-semibold text-[#84dfff] transition hover:bg-[#0a2c3b] hover:text-white"><Edit3 className="h-4 w-4" />Edit profile</button></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><section className="border border-cyan-100/12 bg-[#061923] p-6"><div className="flex items-start gap-4"><img src={user?.avatarUrl || `https://api.dicebear.com/7.x/identicon/svg?seed=${user?.username || 'developer'}`} alt="" className="h-16 w-16 rounded-full border-2 border-[#84dfff]/50 bg-[#092737]" /><div className="min-w-0"><h2 className="truncate text-xl font-semibold text-white">{user?.name || user?.username}</h2><p className="mt-0.5 font-mono text-sm text-[#84dfff]">@{user?.username}</p><p className="mt-2 flex items-center gap-2 text-sm text-slate-400"><Mail className="h-4 w-4" />{user?.email}</p></div></div><div className="mt-6 border-t border-cyan-100/10 pt-5"><p className="text-sm leading-relaxed text-slate-300">{bio}</p></div><div className="mt-5 flex items-center gap-2 border-t border-cyan-100/10 pt-4 text-sm text-emerald-400"><ShieldCheck className="h-4 w-4" />Verified CodeSync account</div></section><section className="border border-cyan-100/12 bg-[#061923]"><div className="border-b border-cyan-100/10 px-6 py-5"><h2 className="font-semibold text-white">Workspace activity</h2><p className="mt-1 text-xs text-slate-400">Based on your actual CodeSync workspaces.</p></div><div className="divide-y divide-cyan-100/10"><ProfileStat icon={<Code2 />} label="Live coding sessions" value={loading ? '—' : rooms.length} /><ProfileStat icon={<Users />} label="Collaborators reached" value={loading ? '—' : memberCount} /><ProfileStat icon={<CalendarDays />} label="Member since" value={user?.createdAt ? new Date(user.createdAt).toLocaleDateString(undefined, { month: 'short', year: 'numeric' }) : '—'} /></div></section></div></div><ProfileEditModal isOpen={editing} onClose={() => setEditing(false)} currentUser={user} onSave={save} /></main>;
};

const ProfileStat = ({ icon, label, value }) => <div className="flex items-center justify-between px-6 py-5"><span className="flex items-center gap-3 text-sm text-slate-400"><span className="text-[#84dfff]">{React.cloneElement(icon, { className: 'h-4 w-4' })}</span>{label}</span><strong className="text-base text-white">{value}</strong></div>;
