import React, { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { AlertCircle, ArrowRight, Check, Loader2 } from 'lucide-react';
import { useAuth } from '../hooks/useAuth.jsx';
import { authService } from '../services/auth.js';
import { AuthDivider, AuthField, AuthFrame } from './LoginPage.jsx';

const GoogleIcon = () => <svg className="h-4 w-4" viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" /><path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" /><path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.06H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.94l2.85-2.22.81-.63z" /><path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.06l3.66 2.84c.87-2.6 3.3-4.52 6.16-4.52z" /></svg>;
const rulesFor = (password) => [{ label: '8+ characters', pass: password.length >= 8 }, { label: 'Uppercase letter', pass: /[A-Z]/.test(password) }, { label: 'Lowercase letter', pass: /[a-z]/.test(password) }, { label: 'Number', pass: /[0-9]/.test(password) }];

export const SignupPage = () => {
  const { register } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [form, setForm] = useState({ name: '', username: '', email: '', password: '', confirmPassword: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const rules = rulesFor(form.password); const passed = rules.filter((rule) => rule.pass).length; const validPassword = passed === rules.length;
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event) => { event.preventDefault(); if (!validPassword) { setError('Use a stronger password that meets all requirements.'); return; } if (form.password !== form.confirmPassword) { setError('Passwords do not match.'); return; } try { setLoading(true); setError(''); await register(form); navigate(`/verify-email?email=${encodeURIComponent(form.email)}`); } catch (err) { setError(err.message || 'Unable to create account.'); } finally { setLoading(false); } };
  return <AuthFrame title="Create your account" subtitle="Set up a shared workspace for your next build."><div className="auth-card auth-card-wide">{error && <div className="auth-error"><AlertCircle className="h-4 w-4 shrink-0" />{error}</div>}<button onClick={() => { window.location.href = authService.getGoogleAuthUrl(); }} type="button" className="auth-google"><GoogleIcon />Continue with Google</button><AuthDivider label="or create an account with email" /><form onSubmit={submit} className="space-y-4"><AuthField label="Full name"><input required name="name" value={form.name} onChange={update} placeholder="Your name" /></AuthField><AuthField label="Username"><input required name="username" value={form.username} onChange={update} placeholder="developer_handle" autoCapitalize="none" /></AuthField><AuthField label="Email address"><input required name="email" type="email" value={form.email} onChange={update} placeholder="Enter a valid email address" /></AuthField><AuthField label="Password"><input required name="password" type="password" value={form.password} onChange={update} placeholder="Create a strong password" minLength="8" /><PasswordStrength rules={rules} passed={passed} visible={Boolean(form.password)} /></AuthField><AuthField label="Confirm password"><input required name="confirmPassword" type="password" value={form.confirmPassword} onChange={update} placeholder="Repeat your password" minLength="8" /><span className={`auth-match ${form.confirmPassword ? (form.password === form.confirmPassword ? 'is-match' : 'is-mismatch') : ''}`}>{form.confirmPassword && (form.password === form.confirmPassword ? 'Passwords match' : 'Passwords do not match')}</span></AuthField><button disabled={loading || !validPassword || form.password !== form.confirmPassword} className="auth-primary">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <>Create account <ArrowRight className="h-4 w-4" /></>}</button></form><p className="auth-footer">Already have an account? <Link to={location.search ? `/login${location.search}` : '/login'}>Sign in</Link></p></div></AuthFrame>;
};

const PasswordStrength = ({ rules, passed, visible }) => visible && <div className="password-strength"><div className="password-meter" aria-label={`Password strength: ${passed} of ${rules.length} requirements met`}>{rules.map((rule) => <i key={rule.label} className={rule.pass ? 'met' : ''} />)}</div><div className="password-rules">{rules.map((rule) => <span key={rule.label} className={rule.pass ? 'met' : ''}><Check className="h-3 w-3" />{rule.label}</span>)}</div></div>;
