import { EXECUTION_STATUS } from '@codesync/shared/constants';

export const JUDGE0_STATUS_IDS = {
  IN_QUEUE: 1,
  PROCESSING: 2,
  ACCEPTED: 3,
  WRONG_ANSWER: 4,
  TIME_LIMIT_EXCEEDED: 5,
  COMPILATION_ERROR: 6,
  SIGSEGV: 7,
  SIGXFSZ: 8,
  SIGFPE: 9,
  SIGABRT: 10,
  NZEC: 11,
  OTHER_RUNTIME_ERROR: 12,
  INTERNAL_ERROR: 13,
  EXEC_FORMAT_ERROR: 14
};

export const JUDGE0_STATUS_MAP = {
  [JUDGE0_STATUS_IDS.IN_QUEUE]: EXECUTION_STATUS.QUEUED,
  [JUDGE0_STATUS_IDS.PROCESSING]: EXECUTION_STATUS.RUNNING,
  [JUDGE0_STATUS_IDS.ACCEPTED]: EXECUTION_STATUS.COMPLETED,
  [JUDGE0_STATUS_IDS.WRONG_ANSWER]: EXECUTION_STATUS.COMPLETED,
  [JUDGE0_STATUS_IDS.TIME_LIMIT_EXCEEDED]: EXECUTION_STATUS.TIME_LIMIT,
  [JUDGE0_STATUS_IDS.COMPILATION_ERROR]: EXECUTION_STATUS.COMPILATION_ERROR,
  [JUDGE0_STATUS_IDS.SIGSEGV]: EXECUTION_STATUS.RUNTIME_ERROR,
  [JUDGE0_STATUS_IDS.SIGXFSZ]: EXECUTION_STATUS.RUNTIME_ERROR,
  [JUDGE0_STATUS_IDS.SIGFPE]: EXECUTION_STATUS.RUNTIME_ERROR,
  [JUDGE0_STATUS_IDS.SIGABRT]: EXECUTION_STATUS.RUNTIME_ERROR,
  [JUDGE0_STATUS_IDS.NZEC]: EXECUTION_STATUS.RUNTIME_ERROR,
  [JUDGE0_STATUS_IDS.OTHER_RUNTIME_ERROR]: EXECUTION_STATUS.RUNTIME_ERROR,
  [JUDGE0_STATUS_IDS.INTERNAL_ERROR]: EXECUTION_STATUS.JUDGE_ERROR,
  [JUDGE0_STATUS_IDS.EXEC_FORMAT_ERROR]: EXECUTION_STATUS.JUDGE_ERROR
};
